SELECT (COUNT(DISTINCT ?profession) AS ?professionCount) WHERE {
  ?cat wdt:P31 wd:Q146 ;
       wdt:P106 ?profession .

  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en" . }
}
